import type { Scenario } from '@/lib/types';

export const SCENARIOS: Scenario[] = [
  {
    id: 1,
    characterId: 'riyaHR',
    channel: 'Email',
    title: 'Urgent: Update Your Personal Information',
    content: "Hi team, we're updating our HR portal. Please confirm your details and upload a copy of your PAN card using this link to avoid payroll issues: hr-cybernova-portal.com",
    correctChoice: 'report',
    attackType: 'Phishing / Pretexting',
    feedback: {
      correct: 'Correct! This is a phishing attempt. The unfamiliar URL and urgent tone are major red flags.',
      incorrect: 'Incorrect. This email uses a suspicious link and urgent language to trick you into giving up sensitive data.',
      tip: 'Always verify HR requests by navigating to the official company intranet or contacting HR through a known channel.',
    },
  },
  {
    id: 2,
    characterId: 'ceoPatel',
    channel: 'SMS',
    title: 'Quick Favor',
    content: "I'm in a conference and need you to buy 10 gift cards for a client urgently. Send me the codes ASAP. I'll reimburse you. - CEO Patel",
    correctChoice: 'verify',
    attackType: 'Whaling / Smishing',
    feedback: {
      correct: 'Excellent choice. An unusual and urgent request, even from the CEO, should be verified through another communication channel, like a phone call.',
      incorrect: 'Be careful! This is a common scam where attackers impersonate executives to rush employees into making financial mistakes.',
      tip: "Verify any unusual financial requests, especially for gift cards, through a different, trusted communication method.",
    },
  },
  {
    id: 3,
    characterId: 'jamieIT',
    channel: 'Chat',
    title: 'Security Scan',
    content: "Hi, this is Jamie from IT. We've detected a vulnerability on your machine. I need to remote in to fix it. Please click here to give me access: secure-it-support.net",
    correctChoice: 'report',
    attackType: 'Impersonation / Tech Scam',
    feedback: {
      correct: 'Spot on! Unsolicited IT support offering to remote into your machine is highly suspicious. This is likely an attempt to install malware.',
      incorrect: 'This is a trap. IT departments usually have scheduled maintenance and will not ask for remote access through a random link.',
      tip: 'Never grant remote access from an unsolicited contact. Always call the official IT helpdesk number to verify the request.',
    },
  },
  {
    id: 4,
    characterId: 'unknownCaller',
    channel: 'Phone',
    title: 'Bank Security Alert',
    content: "(Automated voice) This is an urgent security alert from your bank. We have detected suspicious activity on your account. Please state your full name, account number, and password to verify your identity.",
    correctChoice: 'report',
    attackType: 'Vishing',
    feedback: {
      correct: "Correct. A legitimate bank will never ask for your password over the phone. This is a vishing (voice phishing) attack.",
      incorrect: 'Never give your password over the phone. This is a classic vishing scam to steal your credentials.',
      tip: 'If you receive a suspicious call from your bank, hang up and call the number on the back of your card.',
    },
  },
  {
    id: 5,
    characterId: 'randomStranger',
    channel: 'Physical',
    title: 'Free USB Drive',
    content: 'At a coffee shop near the office, a stranger offers you a free USB drive. "Hey, my company is promoting our new software. Take a freebie, it has a demo on it!"',
    correctChoice: 'report',
    attackType: 'Baiting',
    feedback: {
      correct: 'Great awareness! Accepting and using a USB from an unknown source is a huge security risk. It could contain malware.',
      incorrect: 'This is a classic baiting attack. The "free" USB drive is bait to get you to plug it into your work computer, infecting the network.',
      tip: 'Never plug untrusted media, like a found or gifted USB drive, into your computer.',
    },
  },
  {
    id: 6,
    characterId: 'alexFinance',
    channel: 'Email',
    title: 'Unpaid Invoice - Action Required',
    content: 'Please find attached an urgent overdue invoice from our new vendor, "Sync Solutions". Please process payment today to avoid late fees. Their bank details are in the attached PDF.',
    correctChoice: 'verify',
    attackType: 'Invoice Fraud',
    feedback: {
      correct: "Good call. A request to pay a new vendor or change bank details urgently requires verification with the finance department and the vendor using established contact info.",
      incorrect: 'This could be invoice fraud. Attackers send fake invoices with their own bank details. Always verify changes with your team.',
      tip: 'Always follow company procedure for vetting new vendors and verifying payment detail changes. A phone call is best.',
    },
  },
  {
    id: 7,
    characterId: 'mayaReceptionist',
    channel: 'Physical',
    title: 'Visitor without a pass',
    content: 'You see someone in a hurry, carrying a lot of boxes, trying to get through the office turnstile behind you. They say, "Could you hold the door? My pass is in one of these boxes!"',
    correctChoice: 'verify',
    attackType: 'Tailgating',
    feedback: {
      correct: "Correct. While it feels rude, you should not let them in. Politely direct them to reception to get a visitor's pass.",
      incorrect: 'This is a tailgating attempt. Attackers rely on our willingness to be helpful to bypass physical security.',
      tip: "Be polite but firm. Always require visitors to go through the proper check-in process at reception.",
    },
  },
  {
    id: 8,
    characterId: 'jamieIT',
    channel: 'Chat',
    title: 'Free Pizza for a Survey!',
    content: "Hey! IT is doing a quick survey on user satisfaction. Fill it out and get a voucher for a free pizza! Here's the link: it-survey-cybernova.com",
    correctChoice: 'trust',
    attackType: 'Legitimate Request',
    feedback: {
      correct: "Correct. This seems like a legitimate internal survey. The URL uses the company name, and the offer is a common internal morale booster.",
      incorrect: "While caution is good, this scenario shows signs of a legitimate internal campaign. Always check the URL, but sometimes it's okay to trust.",
      tip: 'Look for signs of legitimacy: internal announcements, familiar URL patterns, and low-risk requests.',
    },
  },
  {
    id: 9,
    characterId: 'socialMediaContact',
    channel: 'Social Media',
    title: 'Fun Quiz!',
    content: 'A post on social media says: "What was your first pet\'s name? And the street you grew up on? Find out your hacker nickname!"',
    correctChoice: 'report',
    attackType: 'Social Media Profiling',
    feedback: {
      correct: 'You spotted it! These "fun" quizzes are designed to gather answers to common security questions used for password resets.',
      incorrect: "This is a trap. You're giving away answers to your security questions, which can be used to take over your accounts.",
      tip: "Be wary of sharing personal details online, even if it seems harmless. This data can be collected and used against you.",
    },
  },
  {
    id: 10,
    characterId: 'friendRequestBot',
    channel: 'Social Media',
    title: 'You have a new connection request',
    content: 'You receive a connection request from someone with a generic profile picture and no mutual connections. Their profile is sparse but has a link: "See my professional portfolio here: profolio-site.biz"',
    correctChoice: 'report',
    attackType: 'Phishing / Impersonation',
    feedback: {
      correct: 'Correct. A generic profile with a suspicious link is a classic sign of a phishing attempt or a bot trying to get you to click on a malicious link.',
      incorrect: 'Be cautious of random connection requests. This is likely an attempt to get you to visit a malicious website.',
      tip: 'Do not accept connection requests from people you do not know, especially if their profile looks fake or they push you to click a link.',
    },
  },
  {
    id: 11,
    characterId: 'ceoPatel',
    channel: 'Email',
    title: 'Project Bluefire Update',
    content: 'Team, please see the latest draft of the confidential Project Bluefire strategy attached. Review and provide feedback by EOD. This is time-sensitive.',
    correctChoice: 'trust',
    attackType: 'Legitimate Request',
    feedback: {
      correct: 'Correct. This is a typical business communication from a known source about a known project. No red flags here.',
      incorrect: 'This is a legitimate email. While the content is sensitive, the sender and context are familiar and expected.',
      tip: 'Context is key. An email that aligns with your current work and comes from a trusted colleague is usually safe.',
    },
  },
  {
    id: 12,
    characterId: 'riyaHR',
    channel: 'Email',
    title: 'Download your new benefits package',
    content: 'Hi! A popup appears on a popular news website you are visiting: "Your system is out of date! Download the new CyberNova Corp security patch to continue browsing safely." It has the company logo.',
    correctChoice: 'report',
    attackType: 'Scareware / Watering Hole',
    feedback: {
      correct: 'Excellent! This is a scareware attack, possibly on a compromised website (a watering hole). Your company would never distribute patches this way.',
      incorrect: 'This is dangerous. Downloading software from a random internet popup, even with a company logo, is a sure way to get malware.',
      tip: 'Only install software and updates from official IT channels. Ignore urgent popups on external websites.',
    },
  },
];
